set_property PACKAGE_PIN G30 [get_ports {clk}]


create_clock -period 1000.00 -name clk -waveform {0.000 5.000} [get_ports clk]

set_false_path -from [get_ports {reset_l}]
set_false_path -to [get_ports {n_select[0]}]
set_false_path -to [get_ports {n_select[1]}]
set_false_path -to [get_ports {n_select[2]}]
set_false_path -to [get_ports {n_select[3]}]
set_false_path -to [get_ports {n_select[4]}]
set_false_path -to [get_ports {n_select[5]}]
set_false_path -to [get_ports {n_select[6]}]
set_false_path -to [get_ports {n_select[7]}]

set_false_path -from [get_ports {q1[1]}]
set_false_path -from [get_ports {q1[2]}]
set_false_path -from [get_ports {q1[3]}]
set_false_path -from [get_ports {q1[4]}]
set_false_path -from [get_ports {q1[5]}]
set_false_path -from [get_ports {q1[6]}]
set_false_path -from [get_ports {q1[7]}]
set_false_path -from [get_ports {q1[0]}]

set_false_path -from [get_ports {q2[1]}]
set_false_path -from [get_ports {q2[2]}]
set_false_path -from [get_ports {q2[3]}]
set_false_path -from [get_ports {q2[4]}]
set_false_path -from [get_ports {q2[5]}]
set_false_path -from [get_ports {q2[6]}]
set_false_path -from [get_ports {q2[7]}]
set_false_path -from [get_ports {q2[0]}]

set_false_path -from [get_ports {q3[1]}]
set_false_path -from [get_ports {q3[2]}]
set_false_path -from [get_ports {q3[3]}]
set_false_path -from [get_ports {q3[4]}]
set_false_path -from [get_ports {q3[5]}]
set_false_path -from [get_ports {q3[6]}]
set_false_path -from [get_ports {q3[7]}]
set_false_path -from [get_ports {q3[0]}]

set_false_path -from [get_ports {q4[1]}]
set_false_path -from [get_ports {q4[2]}]
set_false_path -from [get_ports {q4[3]}]
set_false_path -from [get_ports {q4[4]}]
set_false_path -from [get_ports {q4[5]}]
set_false_path -from [get_ports {q4[6]}]
set_false_path -from [get_ports {q4[7]}]
set_false_path -from [get_ports {q4[0]}]

set_false_path -from [get_ports {q5[1]}]
set_false_path -from [get_ports {q5[2]}]
set_false_path -from [get_ports {q5[3]}]
set_false_path -from [get_ports {q5[4]}]
set_false_path -from [get_ports {q5[5]}]
set_false_path -from [get_ports {q5[6]}]
set_false_path -from [get_ports {q5[7]}]
set_false_path -from [get_ports {q5[0]}]

set_false_path -from [get_ports {q6[1]}]
set_false_path -from [get_ports {q6[2]}]
set_false_path -from [get_ports {q6[3]}]
set_false_path -from [get_ports {q6[4]}]
set_false_path -from [get_ports {q6[5]}]
set_false_path -from [get_ports {q6[6]}]
set_false_path -from [get_ports {q6[7]}]
set_false_path -from [get_ports {q6[0]}]

set_false_path -from [get_ports {q7[1]}]
set_false_path -from [get_ports {q7[2]}]
set_false_path -from [get_ports {q7[3]}]
set_false_path -from [get_ports {q7[4]}]
set_false_path -from [get_ports {q7[5]}]
set_false_path -from [get_ports {q7[6]}]
set_false_path -from [get_ports {q7[7]}]
set_false_path -from [get_ports {q7[0]}]

set_false_path -from [get_ports {q8[1]}]
set_false_path -from [get_ports {q8[2]}]
set_false_path -from [get_ports {q8[3]}]
set_false_path -from [get_ports {q8[4]}]
set_false_path -from [get_ports {q8[5]}]
set_false_path -from [get_ports {q8[6]}]
set_false_path -from [get_ports {q8[7]}]
set_false_path -from [get_ports {q8[0]}]

